In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df_A = pd.read_csv("Datasets\df_A.csv")
df_B = pd.read_csv("Datasets\df_B.csv")

In [8]:
df_A

,LOCATION,DATE_TIME,DATE,TIME,SENSOR_ID,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,A,2020-05-15 00:00:00,2020-05-15,00:00:00,sensor 1,0.0,0.0,0.000,6259559.0,25.184316,22.857507,0.0
1,A,2020-05-15 00:00:00,2020-05-15,00:00:00,sensor 2,0.0,0.0,0.000,6183645.0,25.184316,22.857507,0.0
2,A,2020-05-15 00:00:00,2020-05-15,00:00:00,sensor 3,0.0,0.0,0.000,6987759.0,25.184316,22.857507,0.0
3,A,2020-05-15 00:00:00,2020-05-15,00:00:00,sensor 5,0.0,0.0,0.000,7602960.0,25.184316,22.857507,0.0
4,A,2020-05-15 00:00:00,2020-05-15,00:00:00,sensor 12,0.0,0.0,0.000,7158964.0,25.184316,22.857507,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
68773,A,2020-06-17 23:45:00,2020-06-17,23:45:00,sensor 37,0.0,0.0,5967.000,7287002.0,21.909288,20.427972,0.0
68774,A,2020-06-17 23:45:00,2020-06-17,23:45:00,sensor 39,0.0,0.0,5147.625,7028601.0,21.909288,20.427972,0.0
68775,A,2020-06-17 23:45:00,2020-06-17,23:45:00,sensor 42,0.0,0.0,5819.000,7251204.0,21.909288,20.427972,0.0
68776,A,2020-06-17 23:45:00,2020-06-17,23:45:00,sensor 43,0.0,0.0,5817.000,6583369.0,21.909288,20.427972,0.0
68777,A,2020-06-17 23:45:00,2020-06-17,23:45:00,sensor 44,0.0,0.0,5910.000,7363272.0,21.909288,20.427972,0.0